{% set name = "requests-aws4auth" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ebde0662dccda5023546055ec4cbe4470cae017ecbfce8d368b80b5e4a94d619

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - requests

test:
  imports:
    - requests_aws4auth

about:
  home: https://github.com/sam-washington/requests-aws4auth
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: AWS4 authentication for Requests
  doc_url: https://pypi.org/project/requests-aws4auth/
  dev_url: https://github.com/sam-washington/requests-aws4auth

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - benhuff
    - mwilson8
